### ISSUE TITLE
Ideas bank Idea Shipping container homes

### ISSUE THREAD

**Issue by EcologyNorth501351** [IserveU/IserveU#693] opened 2017-02-17 16:00 UTC
Under the resources page, if someone can remove all the resources. We cant seem remove them when we try to edit. It makes the idea look messy. We don't want to redo and lose the comments for this idea.

Lyle.

**Comment by psaunders** [comment] 2017-02-17 22:55
This is a duplicate of: https://github.com/IserveU/IserveU/issues/664

They'll be stacked as revisions.

**Closed by psaunders** 2017-02-17 22:55 UTC
Labels: wontfix
